version: '3.3'

services:
  redis:
    image: "redis"
    ports:
      - "%{REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD} --replicaof no one --replica-read-only no
    volumes:
      - cache:/data
    labels:
      traefik.enable: "false"
    env_file:
      - .env.prod

  traefik:
    build:
      dockerfile: traefik.Dockerfile
      context: .
    command:
      - "--configFile=traefik.yml"
      - "--providers.docker=true"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefiklogs:/traefiklogs"

  app:
    command: python3 -m gunicorn --bind 0.0.0.0:80 app.wsgi:application
    depends_on:
      - traefik
      - redis
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - staticfiles:/app/static
    ports:
      - 80
    env_file:
      - .env.prod
    labels:
      traefik.enable: true
      traefik.http.routers.app.rule: Host(`${HOST}`)
      traefik.http.routers.app.entrypoints: http
      traefik.http.routers.app.middlewares: redirect
      traefik.http.middlewares.redirect.redirectscheme.scheme: https
      traefik.http.routers.app-secure.rule: Host(`${HOST}`)
      traefik.http.routers.app-secure.entrypoints: https
      traefik.http.routers.app-secure.tls.certresolver: ssl
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https
      traefik.http.services.app-service.loadbalancer.healthcheck.path: /health-check
      traefik.http.services.app-service.loadbalancer.healthcheck.timeout: 2s
      traefik.http.services.app-service.loadbalancer.healthcheck.interval: 5s
      traefik.http.services.app-service.loadbalancer.healthcheck.hostname: ${HOST}

  celery-scheduler:
    build: .
    entrypoint: []
    env_file:
      - .env.prod
    command: python -m celery -A app beat
    depends_on:
      - app
    environment:
      - REDIS_HOST=redis
    labels:
      - "traefik.enable=false"

  celery-worker:
    build: .
    env_file:
      - .env.prod
    entrypoint: [ "sh", "/app/entrypoint.worker.sh" ]
    command: python -m celery -A app worker --events
    depends_on:
      - app
    environment:
      - REDIS_HOST=redis
    labels:
      - "traefik.enable=false"

  nginx:
    depends_on:
      - traefik
      - app
    image: nginx:alpine
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/app/static
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.rule: Host(`${HOST}`) && PathPrefix(`/static`)
      traefik.http.routers.nginx.entrypoints: http
      traefik.http.services.nginx.loadbalancer.server.port: "80"
      traefik.http.routers.nginx-secure.rule: Host(`${HOST}`) && PathPrefix(`/static`)
      traefik.http.routers.nginx-secure.entrypoints: https
      traefik.http.routers.nginx-secure.tls.certresolver: ssl
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https

volumes:
  cache:
  staticfiles:
