version: "3.3"
services:
  redis:
    extends:
      file: compose-common.yml
      service: redis

  traefik:
    extends:
      file: compose-common.yml
      service: traefik

  api:
    extends:
      file: compose-common.yml
      service: api
    command: python3 manage.py runserver 0.0.0.0:80
    depends_on:
      - db
      - traefik
      - redis
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis
      - FLOWER_HOST=flower

  db:
    extends:
      file: compose-common.yml
      service: db
    ports:
      - "${SQL_PORT}:${SQL_PORT}"

    command: -p ${SQL_PORT}
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DATABASE}

  celery-scheduler:
    extends:
      file: compose-common.yml
      service: celery-scheduler
    entrypoint: []
    depends_on:
      - api
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis

  celery-worker:
    extends:
      file: compose-common.yml
      service: celery-worker
    entrypoint: []
    depends_on:
      - api
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis

  flower:
    extends:
      file: compose-common.yml
      service: flower
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"


volumes:
  postgres_data:
  logs:
  cache:
  .:
