version: "3.3"
services:
  redis:
    image: "redis"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server
    volumes:
      - cache:/data

  traefik:
    build:
      dockerfile: traefik.Dockerfile
      context: .
    command:
      - "--configFile=traefik.yml"
      - "--providers.docker=true"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefiklogs:/traefiklogs"

  app:
    build: .
    volumes:
      - .:/app/
    ports:
      - 80
    env_file:
      - .env.dev

    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`${HOST}`)
      traefik.http.routers.api.entrypoints: http
    command: python3 manage.py runserver 0.0.0.0:80
    depends_on:
      - db
      - traefik
      - redis
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis
      - FLOWER_HOST=flower

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${SQL_PORT}:${SQL_PORT}"

    command: -p ${SQL_PORT}
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DATABASE}

  celery-scheduler:
    build: .
    env_file:
      - .env.dev
    command: python -m celery -A app beat
    volumes:
      - .:/app/
    entrypoint: []
    depends_on:
      - app
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis

  celery-worker:
    build: .
    env_file:
      - .env.dev
    command: python -m celery -A app worker -P solo --concurrency 1 --events
    volumes:
      - .:/app/
    entrypoint: []
    depends_on:
      - app
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis

  flower:
    build: .
    env_file:
      - .env.dev
    entrypoint: []
    command: python -m celery -A app flower --address=0.0.0.0 --port=${FLOWER_PORT}
    environment:
      - SQL_HOST=db
      - REDIS_HOST=redis
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"

  nginx:
    depends_on:
      - traefik
      - app
    image: nginx:alpine
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/app/static
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.rule: Host(`${HOST}`) && PathPrefix(`/static`)
      traefik.http.routers.nginx.entrypoints: http
      traefik.http.services.nginx.loadbalancer.server.port: "80"

volumes:
  staticfiles:
  postgres_data:
  cache:
  .:
