[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.black]
line-length = 100
extend-exclude = """
migrations
"""

[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.pdm.scripts]
_.env_file = ".env.dev"
collectstatic.cmd = "python manage.py collectstatic --noinput"
makemigrations.cmd = "python manage.py makemigrations"
migrate.cmd = "python manage.py migrate"
server.cmd = "python manage.py runserver"
createsuperuser.cmd = "python manage.py createsuperuser"
makemessages.shell = "cd src && pdm run python manage.py makemessages"
compilemessages.shell = "cd src && pdm run python manage.py compilemessages"
tests.shell = """\
coverage run --source=src/ --rcfile=.coveragerc -m pytest tests/ \
&& \
coverage html \
&& \
google-chrome htmlcov/index.html
"""


[tool.pdm.dev-dependencies]
dev = [
    "black>=22.1.0",
    "pytest==7.0.1",
    "pytest-django>=4.5.2",
    "mypy>=0.931",
    "django-debug-toolbar>=3.5",
    "coverage==6.3.2",
    "pre-commit>=2.19.0"]
[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE='app.settings.test'
testpaths = [
    "tests/",
]
addopts = "--rootdir ./tests --disable-warnings"

[project]
name = "boilerplate"
version = "0.1.0"
description = ""
authors = [
    {name = "Leandro de Souza", email = "leandrodesouzadev@gmail.com"},
]
license-expression = "MIT"
dependencies = [
    "Django==4.0",
    "djangorestframework>=3.13.1",
    "celery[redis]>=5.2.7",
    "whitenoise>=6.2.0",
    "django-environ>=0.9.0",
    "django-jazzmin>=2.5.0",
    "drf-spectacular[sidecar]>=0.22.1",
    "django-cors-headers>=3.13.0",
    "psycopg2-binary>=2.9.3",
    "djangorestframework-simplejwt>=5.2.0",
    "setuptools>=62.6.0",
    "channels>=3.0.5",
    "channels-redis>=3.4.0",
    "daphne>=3.0.2",
    "django-extensions>=3.1.5",
]
requires-python = ">=3.9"

[project.urls]
Homepage = ""

[project.optional-dependencies]
