version: "3.3"

services:
  django: &django
    command: python3 -m gunicorn --bind 0.0.0.0:80 app.wsgi:application
    depends_on:
      db_migration:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: infra/app/Dockerfile
    volumes:
      - staticfiles:/app/storage/static
      - translations:/app/locale
    ports:
      - 80
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      SQL_HOST: db
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
    networks:
      - shared

  db_migration:
    <<: *django
    command: python manage.py migrate
    entrypoint: ["sh", "/app/before_migrate.sh"]
    ports: []
    depends_on: []

  celery-scheduler:
    <<: *django
    command: python -m celery -A app beat
    ports: []

  celery-worker:
    <<: *django
    command: python -m celery -A app worker --events
    ports: []

volumes:
  staticfiles:
    external: true
    name: staticfiles
  translations:

networks:
  shared:
    external: true
