global:
  sendAnonymousUsage: false

providers:
  docker: {}

entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

certificatesResolvers:
  ssl:
    acme:
      httpChallenge:
        entryPoint: http
      email: leandrodesouzadev@gmail.com
      storage: /letsencrypt/acme.json

accessLog:
  filePath: "/traefiklogs/access.log"
  format: json
  fields:
    defaultMode: drop
    names:
      ClientHost: keep
      DownstreamStatus: keep
      DownstramContentSize: keep
      OriginDuration: keep
      OriginStatus: keep
      RequestMethod: keep
      RequestPath: keep
      RequestProtocol: keep
      ServiceName: keep
      StartUTC: keep

    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        Content-Type: keep
