from app.settings.env import env

MESSAGING_EXTERNAL_SERVICE_BACKEND = env("MESSAGING_EXTERNAL_SERVICE_BACKEND", default="dev.stdout")

if MESSAGING_EXTERNAL_SERVICE_BACKEND == "discord":
    MESSAGING_EXTERNAL_SERVICE_DISCORD_OAUTH_TOKEN = env(
        "MESSAGING_EXTERNAL_SERVICE_DISCORD_OAUTH_TOKEN"
    )
