from app.settings.env import env

SMS_EXTERNAL_SERVICE_BACKEND = env("SMS_EXTERNAL_SERVICE_BACKEND", default="dev.stdout")

if SMS_EXTERNAL_SERVICE_BACKEND == "twilio":
    TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
    TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
    TWILIO_SERVICE_PHONE = env("TWILIO_SERVICE_PHONE")
