# Generated by Django 4.1 on 2022-08-30 16:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DjangoGroupProxy",
        ),
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={
                "verbose_name": "User Group",
                "verbose_name_plural": "User Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default="", max_length=255, verbose_name="Full name"),
            preserve_default=False,
        ),
    ]
