# Generated by Django 3.2.10 on 2022-03-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
