# Generated by Django 4.1 on 2022-08-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_djangogroupproxy_group_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
