# Generated by Django 4.2 on 2023-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_is_active_alter_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_token",
            field=models.CharField(
                blank=True,
                help_text="The token used to send push notifications to the user's phone",
                max_length=128,
                null=True,
                verbose_name="Notification token",
            ),
        ),
    ]
