class HttpStatusCode:
    HTTP_100_CONTINUE = 100
    HTTP_101_SWITCHING_PROTOCOLS = 101
    HTTP_102_PROCESSING = 102
    HTTP_103_EARLY_HINTS = 103
    HTTP_200_OK = 200
    HTTP_201_CREATED = 201
    HTTP_202_ACCEPTED = 202
    HTTP_203_NON_AUTHORITATIVE_INFORMATION = 203
    HTTP_204_NO_CONTENT = 204
    HTTP_205_RESET_CONTENT = 205
    HTTP_206_PARTIAL_CONTENT = 206
    HTTP_207_MULTI_STATUS = 207
    HTTP_208_ALREADY_REPORTED = 208
    HTTP_226_IM_USED = 226
    HTTP_300_MULTIPLE_CHOICES = 300
    HTTP_301_MOVED_PERMANENTLY = 301
    HTTP_302_FOUND = 302
    HTTP_303_SEE_OTHER = 303
    HTTP_304_NOT_MODIFIED = 304
    HTTP_305_USE_PROXY = 305
    HTTP_306_RESERVED = 306
    HTTP_307_TEMPORARY_REDIRECT = 307
    HTTP_308_PERMANENT_REDIRECT = 308
    HTTP_400_BAD_REQUEST = 400
    HTTP_401_UNAUTHORIZED = 401
    HTTP_402_PAYMENT_REQUIRED = 402
    HTTP_403_FORBIDDEN = 403
    HTTP_404_NOT_FOUND = 404
    HTTP_405_METHOD_NOT_ALLOWED = 405
    HTTP_406_NOT_ACCEPTABLE = 406
    HTTP_407_PROXY_AUTHENTICATION_REQUIRED = 407
    HTTP_408_REQUEST_TIMEOUT = 408
    HTTP_409_CONFLICT = 409
    HTTP_410_GONE = 410
    HTTP_411_LENGTH_REQUIRED = 411
    HTTP_412_PRECONDITION_FAILED = 412
    HTTP_413_REQUEST_ENTITY_TOO_LARGE = 413
    HTTP_414_REQUEST_URI_TOO_LONG = 414
    HTTP_415_UNSUPPORTED_MEDIA_TYPE = 415
    HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE = 416
    HTTP_417_EXPECTATION_FAILED = 417
    HTTP_418_IM_A_TEAPOT = 418
    HTTP_421_MISDIRECTED_REQUEST = 421
    HTTP_422_UNPROCESSABLE_ENTITY = 422
    HTTP_423_LOCKED = 423
    HTTP_424_FAILED_DEPENDENCY = 424
    HTTP_425_TOO_EARLY = 425
    HTTP_426_UPGRADE_REQUIRED = 426
    HTTP_428_PRECONDITION_REQUIRED = 428
    HTTP_429_TOO_MANY_REQUESTS = 429
    HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
    HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS = 451
    HTTP_500_INTERNAL_SERVER_ERROR = 500
    HTTP_501_NOT_IMPLEMENTED = 501
    HTTP_502_BAD_GATEWAY = 502
    HTTP_503_SERVICE_UNAVAILABLE = 503
    HTTP_504_GATEWAY_TIMEOUT = 504
    HTTP_505_HTTP_VERSION_NOT_SUPPORTED = 505
    HTTP_506_VARIANT_ALSO_NEGOTIATES = 506
    HTTP_507_INSUFFICIENT_STORAGE = 507
    HTTP_508_LOOP_DETECTED = 508
    HTTP_509_BANDWIDTH_LIMIT_EXCEEDED = 509
    HTTP_510_NOT_EXTENDED = 510
    HTTP_511_NETWORK_AUTHENTICATION_REQUIRED = 511


HTTP_STATUS_NAME = {
    HttpStatusCode.HTTP_100_CONTINUE: "Continue",
    HttpStatusCode.HTTP_101_SWITCHING_PROTOCOLS: "Switching Protocols",
    HttpStatusCode.HTTP_102_PROCESSING: "Processing",
    HttpStatusCode.HTTP_103_EARLY_HINTS: "Early Hints",
    HttpStatusCode.HTTP_200_OK: "Ok",
    HttpStatusCode.HTTP_201_CREATED: "Created",
    HttpStatusCode.HTTP_202_ACCEPTED: "Accepted",
    HttpStatusCode.HTTP_203_NON_AUTHORITATIVE_INFORMATION: "Non Authoritative Information",
    HttpStatusCode.HTTP_204_NO_CONTENT: "No Content",
    HttpStatusCode.HTTP_205_RESET_CONTENT: "Reset Content",
    HttpStatusCode.HTTP_206_PARTIAL_CONTENT: "Partial Content",
    HttpStatusCode.HTTP_207_MULTI_STATUS: "Multi Status",
    HttpStatusCode.HTTP_208_ALREADY_REPORTED: "Already Reported",
    HttpStatusCode.HTTP_226_IM_USED: "Im Used",
    HttpStatusCode.HTTP_300_MULTIPLE_CHOICES: "Multiple Choices",
    HttpStatusCode.HTTP_301_MOVED_PERMANENTLY: "Moved Permanently",
    HttpStatusCode.HTTP_302_FOUND: "Found",
    HttpStatusCode.HTTP_303_SEE_OTHER: "See Other",
    HttpStatusCode.HTTP_304_NOT_MODIFIED: "Not Modified",
    HttpStatusCode.HTTP_305_USE_PROXY: "Use Proxy",
    HttpStatusCode.HTTP_306_RESERVED: "Reserved",
    HttpStatusCode.HTTP_307_TEMPORARY_REDIRECT: "Temporary Redirect",
    HttpStatusCode.HTTP_308_PERMANENT_REDIRECT: "Permanent Redirect",
    HttpStatusCode.HTTP_400_BAD_REQUEST: "Bad Request",
    HttpStatusCode.HTTP_401_UNAUTHORIZED: "Unauthorized",
    HttpStatusCode.HTTP_402_PAYMENT_REQUIRED: "Payment Required",
    HttpStatusCode.HTTP_403_FORBIDDEN: "Forbidden",
    HttpStatusCode.HTTP_404_NOT_FOUND: "Not Found",
    HttpStatusCode.HTTP_405_METHOD_NOT_ALLOWED: "Method Not Allowed",
    HttpStatusCode.HTTP_406_NOT_ACCEPTABLE: "Not Acceptable",
    HttpStatusCode.HTTP_407_PROXY_AUTHENTICATION_REQUIRED: "Proxy Authentication Required",
    HttpStatusCode.HTTP_408_REQUEST_TIMEOUT: "Request Timeout",
    HttpStatusCode.HTTP_409_CONFLICT: "Conflict",
    HttpStatusCode.HTTP_410_GONE: "Gone",
    HttpStatusCode.HTTP_411_LENGTH_REQUIRED: "Length Required",
    HttpStatusCode.HTTP_412_PRECONDITION_FAILED: "Precondition Failed",
    HttpStatusCode.HTTP_413_REQUEST_ENTITY_TOO_LARGE: "Request Entity Too Large",
    HttpStatusCode.HTTP_414_REQUEST_URI_TOO_LONG: "Request Uri Too Long",
    HttpStatusCode.HTTP_415_UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type",
    HttpStatusCode.HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
    HttpStatusCode.HTTP_417_EXPECTATION_FAILED: "Expectation Failed",
    HttpStatusCode.HTTP_418_IM_A_TEAPOT: "Im A Teapot",
    HttpStatusCode.HTTP_421_MISDIRECTED_REQUEST: "Misdirected Request",
    HttpStatusCode.HTTP_422_UNPROCESSABLE_ENTITY: "Unprocessable Entity",
    HttpStatusCode.HTTP_423_LOCKED: "Locked",
    HttpStatusCode.HTTP_424_FAILED_DEPENDENCY: "Failed Dependency",
    HttpStatusCode.HTTP_425_TOO_EARLY: "Too Early",
    HttpStatusCode.HTTP_426_UPGRADE_REQUIRED: "Upgrade Required",
    HttpStatusCode.HTTP_428_PRECONDITION_REQUIRED: "Precondition Required",
    HttpStatusCode.HTTP_429_TOO_MANY_REQUESTS: "Too Many Requests",
    HttpStatusCode.HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
    HttpStatusCode.HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable For Legal Reasons",
    HttpStatusCode.HTTP_500_INTERNAL_SERVER_ERROR: "Internal Server Error",
    HttpStatusCode.HTTP_501_NOT_IMPLEMENTED: "Not Implemented",
    HttpStatusCode.HTTP_502_BAD_GATEWAY: "Bad Gateway",
    HttpStatusCode.HTTP_503_SERVICE_UNAVAILABLE: "Service Unavailable",
    HttpStatusCode.HTTP_504_GATEWAY_TIMEOUT: "Gateway Timeout",
    HttpStatusCode.HTTP_505_HTTP_VERSION_NOT_SUPPORTED: "Ion Not Supported",
    HttpStatusCode.HTTP_506_VARIANT_ALSO_NEGOTIATES: "Variant Also Negotiates",
    HttpStatusCode.HTTP_507_INSUFFICIENT_STORAGE: "Insufficient Storage",
    HttpStatusCode.HTTP_508_LOOP_DETECTED: "Loop Detected",
    HttpStatusCode.HTTP_509_BANDWIDTH_LIMIT_EXCEEDED: "Bandwidth Limit Exceeded",
    HttpStatusCode.HTTP_510_NOT_EXTENDED: "Not Extended",
    HttpStatusCode.HTTP_511_NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
}
