# Generated by Django 4.2 on 2023-09-25 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("last_updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("source_object_id", models.IntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("int_comm", "Internal communication")],
                        help_text="The kind of notification",
                        max_length=16,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="This is the text that shows on the top of the notification",
                        max_length=65,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="This is the text that contains the details of the notification",
                        max_length=240,
                        verbose_name="Description",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="The additional data that is sent with the notification",
                        verbose_name="Additional data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("c", "Created"),
                            ("e", "Enqueued"),
                            ("s", "Sent"),
                            ("d", "Delivered"),
                            ("r", "Read"),
                            ("f", "Failed"),
                        ],
                        help_text="The current status of this notification",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "push_ticket_id",
                    models.CharField(
                        blank=True,
                        help_text="The notification service ID for this notification, with this receipt ID we can check if the message was delivered",
                        max_length=36,
                        null=True,
                        verbose_name="Receipt ID",
                    ),
                ),
                (
                    "delivery_attempts",
                    models.SmallIntegerField(
                        blank=True,
                        default=1,
                        help_text="How many times we tried to deliver this notification",
                        verbose_name="Delivery attempts",
                    ),
                ),
                (
                    "failure_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DeviceNotRegistered", "Device not registered"),
                            ("MessageTooBig", "Message too big"),
                            ("MessageRateExceeded", "Message rate exceeded"),
                            ("MismatchSenderId", "Mismatch sender ID"),
                            ("InvalidCredentials", "Invalid credentials"),
                            ("NotOptedIn", "Not opted-in"),
                            ("TooManyDeliveryAttempts", "Too many delivery attempts"),
                        ],
                        help_text="When the notification fails this was the reason provided",
                        max_length=32,
                        null=True,
                        verbose_name="Failure kind",
                    ),
                ),
                (
                    "failure_message",
                    models.CharField(
                        blank=True,
                        help_text="The message provided of the cause of the failure",
                        max_length=256,
                        null=True,
                        verbose_name="Failure message",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The exact time that this notification was marked as read by the end-user",
                        null=True,
                        verbose_name="Read at",
                    ),
                ),
                (
                    "delivery_confirmation_received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the provider of this notification confirmed the delivery of this notification",
                        null=True,
                        verbose_name="Delivery confirmation received at",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="push_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Notification",
                "verbose_name_plural": "Push Notifications",
            },
        ),
    ]
