# Generated by Django 4.2 on 2023-09-25 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("push_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="push_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
