from app.settings.env import env

SEND_ERROR_REPORT_ON_FAILURES = env.bool("SEND_ERROR_REPORT_ON_FAILURES", default=False)
SEND_ERROR_REPORT_ON_LANGUAGE = env("SEND_ERROR_REPORT_ON_LANGUAGE", default="en-us")
MESSAGING_EXTERNAL_SERVICE_BACKEND = env("MESSAGING_EXTERNAL_SERVICE_BACKEND", default="dev.stdout")


if MESSAGING_EXTERNAL_SERVICE_BACKEND == "dev.stdout":
    ERROR_REPORT_REQUEST_CHANNEL_ID = ""
    ERROR_REPORT_TASK_CHANNEL_ID = ""
else:
    ERROR_REPORT_REQUEST_CHANNEL_ID = env("ERROR_REPORT_REQUEST_CHANNEL_ID")
    ERROR_REPORT_TASK_CHANNEL_ID = env("ERROR_REPORT_TASK_CHANNEL_ID")
