version: "3.3"

services:
  redis:
    image: "redis"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD} --replicaof no one --replica-read-only no
    volumes:
      - cache:/data
    networks:
      - shared

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    command: -p ${SQL_PORT}
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DATABASE}
    networks:
      - shared

volumes:
  cache:
  postgres_data:

networks:
  shared:
    external: true
