name: Deploy to Staging/Development

on:
  push:
    branches: [dev]
    paths:
      - "**.py"

jobs:
  deploy_to_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Dump event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Deploy new changes
        uses: appleboy/ssh-action@v1.0.0
        env:
          PROJECT_ROOT: ${{github.event.repository.name}}
        with:
          host: ${{secrets.STAGING_SSH_HOSTNAME}}
          username: ${{secrets.STAGING_USER_NAME}}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          envs: PROJECT_ROOT,
          script_stop: true
          script: |
            cd $PROJECT_ROOT
            git fetch --all
            git reset --hard origin/dev
            git pull origin dev
            docker compose -f staging.yml --env-file .env build --build-arg="PDM_INSTALL_ARGS=--prod --no-lock --no-editable"
            docker compose -f staging.yml --env-file .env up db_migration --no-deps -d
            docker compose -f staging.yml --env-file .env up django celery-scheduler celery-worker --no-deps -d
