# type: ignore
from typing import List

from .common import *

THIRD_PARTY_APPS += ["storages"]
INSTALLED_APPS: List[str] = DJANGO_APPS + THIRD_PARTY_APPS + YOUR_PROJECT_APPS

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", str)
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", str)
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", str)
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_MEDIA_LOCATION = "media/"
DEFAULT_FILE_STORAGE = "app.ext.storage.aws_s3.PrivateMediaStorage"


STATIC_ROOT: str = os.path.join(BASE_DIR, "static")

SECURE_SSL_REDIRECT = env("DJANGO_SECURE_SSL_REDIRECT", bool)
CSRF_COOKIE_SECURE = env("DJANGO_CSRF_COOKIE_SECURE", bool)
SECURE_HSTS_SECONDS = env("DJANGO_SECURE_HSTS_SECONDS", int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", bool)
SECURE_HSTS_PRELOAD = env("DJANGO_SECURE_HSTS_PRELOAD", bool)
SESSION_COOKIE_SECURE = env("DJANGO_SESSION_COOKIE_SECURE", bool)

EMAIL_BACKEND = "app.ext.email.send_grid.SendGridEmailBackend"
SENDGRID_API_KEY = env("SENDGRID_API_KEY", default="")
