# type: ignore
from typing import List

from .common import *

INSTALLED_APPS: List[str] = DJANGO_APPS + THIRD_PARTY_APPS + YOUR_PROJECT_APPS

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

STATIC_ROOT: str = os.path.join(BASE_DIR, "static")

SECURE_SSL_REDIRECT = env("DJANGO_SECURE_SSL_REDIRECT", bool)
CSRF_COOKIE_SECURE = env("DJANGO_CSRF_COOKIE_SECURE", bool)
SECURE_HSTS_SECONDS = env("DJANGO_SECURE_HSTS_SECONDS", int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", bool)
SECURE_HSTS_PRELOAD = env("DJANGO_SECURE_HSTS_PRELOAD", bool)
SESSION_COOKIE_SECURE = env("DJANGO_SESSION_COOKIE_SECURE", bool)

EMAIL_BACKEND = "app.ext.email.send_grid.SendGridEmailBackend"
SENDGRID_API_KEY = env("SENDGRID_API_KEY", default="")
